package com.riverheadny.budget.ui.screens.budget.spendingreduction

import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.riverheadny.budget.data.models.Budget2027ScenarioModel
import com.riverheadny.budget.data.models.Budget2027TaxCapOffsetModel
import com.riverheadny.budget.data.models.CloseTheGap2027
import com.riverheadny.budget.data.models.DepartmentBudgetLensData
import com.riverheadny.budget.ui.components.HeroCard
import com.riverheadny.budget.ui.components.PageColumn
import com.riverheadny.budget.ui.components.currency
import com.riverheadny.budget.ui.theme.BrandMint
import com.riverheadny.budget.ui.theme.BrandNavy
import com.riverheadny.budget.ui.theme.CardSurface
import com.riverheadny.budget.ui.theme.MutedText
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

private data class SpendingReductionItem(
    val id: String,
    val title: String,
    val amount: Double,
    val source: String,
    val rationale: String,
    val confidence: String? = null,   // "firm" | "moderate" | "volatile" (supplement trims)
)

// Itemized, ledger-sourced trims from the 2026 Budget Supplement, generated by
// the shared etl/parse_budget_supplement.py and bundled as an asset.
@Serializable
private data class SupplementReductionRaw(
    val account: String,
    val name: String,
    val fund: String = "",
    val fundName: String = "",
    val actual2024: Double? = null,
    val ytd2025: Double? = null,
    val tentative2026: Double? = null,
    val target: Double,
    val confidence: String,
)

@Serializable
private data class SupplementReductionsFile(val total: Double, val items: List<SupplementReductionRaw>)

private val supplementJson = Json { ignoreUnknownKeys = true }

private fun confidenceRationale(c: String): String = when (c) {
    "firm" -> "Operating or professional-services line budgeted well above its own trailing actuals — the firmest kind of trim."
    "moderate" -> "Capital or maintenance line that fluctuates year to year; the trim depends on 2027 project timing."
    "volatile" -> "Price-driven (fuel, energy, utilities); the excess over trend is real but not guaranteed to recur."
    else -> ""
}

private fun loadSupplementItems(context: Context): List<SpendingReductionItem> = try {
    val text = context.assets.open("data/budget-supplement/reductions.json").bufferedReader().use { it.readText() }
    supplementJson.decodeFromString<SupplementReductionsFile>(text).items.map { r ->
        SpendingReductionItem(
            id = "supp-${r.account}",
            title = r.name,
            amount = r.target,
            source = "${r.fundName} — 2026 tentative ${currency(r.tentative2026 ?: 0.0)} vs 2024 actual ${currency(r.actual2024 ?: 0.0)}; trims to the trailing run-rate",
            rationale = confidenceRationale(r.confidence),
            confidence = r.confidence,
        )
    }.sortedByDescending { it.amount }
} catch (e: Exception) {
    emptyList()
}

private val personnelPolicyItems: List<SpendingReductionItem> = listOf(
    SpendingReductionItem(
        "healthcare", "20% healthcare premium contribution",
        Budget2027TaxCapOffsetModel.healthcareContributionSavings,
        "22 eligible senior-staff/elected positions x NYSHIP Empire Plan participating-agency individual premium (${currency(Budget2027TaxCapOffsetModel.nyshipPlanPrimeIndividualMonthlyPremium)}/mo) x 20%",
        "Requires a policy adoption for exempt and elected positions; represented staff would need successor bargaining.",
    ),
    SpendingReductionItem(
        "overtime", "Police Uniform OT recovery target",
        Budget2027TaxCapOffsetModel.overtimeControlSavings,
        "2024 actual (${currency(Budget2027TaxCapOffsetModel.policeUniformOTActual2024)}) vs. ${currency(Budget2027TaxCapOffsetModel.policeUniformOTBudget2024)} budget — a ${currency(Budget2027TaxCapOffsetModel.policeUniformOTVariance)} variance",
        "Southampton's 2026 adopted Police OT is \$13,069.50/officer for 113 officers; at that regional rate Riverhead's ~100 officers would need about \$1,306,950 — meaning most of the variance is likely real coverage need, not scheduling waste. Zero OT isn't realistic, so this targets only the residual above that peer benchmark.",
    ),
    SpendingReductionItem(
        "retirementRefill", "Targeted retirement + refill control",
        Budget2027TaxCapOffsetModel.targetedRetirementRefillSavings,
        "Three modeled senior departures, two lower-cost backfills",
        "Depends on which positions actually turn over in 2027; not guaranteed.",
    ),
    SpendingReductionItem(
        "vacancyFactor", "1% civilian vacancy factor",
        Budget2027TaxCapOffsetModel.civilianVacancyFactorSavings,
        "1% applied to the 2026 civilian/CSEA payroll base",
        "Assumes normal turnover timing, not a headcount reduction.",
    ),
    SpendingReductionItem(
        "exemptRaiseHold", "Hold exempt discretionary raises",
        Budget2027TaxCapOffsetModel.exemptRaiseHoldSavings,
        "2026 exempt discretionary raise baseline",
        "A Board choice each budget cycle, not a structural change.",
    ),
    SpendingReductionItem(
        "electedRaiseHold", "Hold elected salary growth",
        Budget2027TaxCapOffsetModel.electedRaiseHoldSavings,
        "2026 elected-official raise baseline",
        "Separately stated Board action, not embedded in the baseline.",
    ),
)

private val operationalItems: List<SpendingReductionItem> =
    DepartmentBudgetLensData.rebalancedSpending
        .filter { it.tighten && !it.isFundNeutralReclassification }
        .map {
            SpendingReductionItem(
                it.account, it.account, it.change,
                "${it.fundFunction} — ${currency(it.adopted2025)} (2025) -> ${currency(it.adopted2026)} (2026), ${it.changeLabel ?: ""}",
                it.rationale,
            )
        }
        .sortedByDescending { it.amount }

@Composable
fun SpendingReductionScreen() {
    val context = LocalContext.current
    val supplementItems = remember { loadSupplementItems(context) }
    val allItems = remember(supplementItems) { personnelPolicyItems + operationalItems + supplementItems }

    var deselected by remember { mutableStateOf(setOf<String>()) }
    fun isSelected(id: String) = id !in deselected
    fun toggle(id: String) {
        deselected = if (id in deselected) deselected - id else deselected + id
    }

    val personnelSelected = personnelPolicyItems.filter { isSelected(it.id) }.sumOf { it.amount }
    val operationalSelected = operationalItems.filter { isSelected(it.id) }.sumOf { it.amount }
    val supplementSelected = supplementItems.filter { isSelected(it.id) }.sumOf { it.amount }
    val grandSelected = personnelSelected + operationalSelected + supplementSelected
    val personnelFullTotal = Budget2027TaxCapOffsetModel.recurringSavingsPackageTotal
    val operationalFullTotal = DepartmentBudgetLensData.operationalGrowthControlTotal
    val supplementFullTotal = supplementItems.sumOf { it.amount }
    val grandFullTotal = personnelFullTotal + operationalFullTotal + supplementFullTotal
    val payrollPressureGap = Budget2027ScenarioModel.modeledAutomaticPayrollPressure
    // Uncapped ratio — with the supplement trims this exceeds 100%, the headline.
    val rawCoverage = if (payrollPressureGap > 0) grandSelected / payrollPressureGap else 0.0
    val coverage = rawCoverage.coerceAtMost(1.0)

    // The real binding constraint: the cap-piercing gap, closed with only firm
    // items + the unanimous buyout.
    val firmSupplementTotal = supplementItems.filter { it.confidence == "firm" }.sumOf { it.amount }
    val firmRecurringTotal = personnelFullTotal + operationalFullTotal + firmSupplementTotal
    val capGap = CloseTheGap2027.capPiercingGap
    val comboLowPct = ((CloseTheGap2027.RetirementIncentive.projectedSavingsLow + firmRecurringTotal) / capGap * 100).toInt()
    val comboHighPct = ((CloseTheGap2027.RetirementIncentive.projectedSavingsHigh + firmRecurringTotal) / capGap * 100).toInt()

    PageColumn {
        HeroCard(
            eyebrow = "Budget",
            title = "2027 Spending Reduction",
            body = "A real, sourced recurring spending-reduction package for the 2027 budget — not a wishlist. Toggle items to build your own package and watch it move against the modeled payroll-pressure gap.",
        )

        Card(shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = CardSurface)) {
            Column(modifier = Modifier.fillMaxWidth().padding(18.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                Text("YOUR SELECTED PACKAGE", color = MutedText, style = MaterialTheme.typography.labelMedium, fontWeight = FontWeight.Bold)
                Text(currency(grandSelected), color = BrandMint, style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Black)
                Text("out of ${currency(grandFullTotal)} available", color = MutedText, style = MaterialTheme.typography.bodySmall)

                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(8.dp)
                        .background(Color(0xFFE2E8F0), RoundedCornerShape(999.dp)),
                ) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth(coverage.toFloat())
                            .height(8.dp)
                            .background(BrandMint, RoundedCornerShape(999.dp)),
                    ) {}
                }
                Text(
                    "${(rawCoverage * 100).toInt()}% of the ${currency(payrollPressureGap)} modeled 2027 payroll-pressure gap${if (rawCoverage >= 1.0) " — fully covered" else ""}",
                    color = MutedText,
                    style = MaterialTheme.typography.labelSmall,
                )

                Row(horizontalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.fillMaxWidth()) {
                    MetricTile("Personnel & policy", personnelSelected, BrandNavy, Modifier.weight(1f))
                    MetricTile("Operational control", operationalSelected, Color(0xFFB45309), Modifier.weight(1f))
                }
                if (supplementItems.isNotEmpty()) {
                    MetricTile("Line-item trims", supplementSelected, Color(0xFF1F5F8F), Modifier.fillMaxWidth())
                }

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedButton(onClick = { deselected = emptySet() }) { Text("Select all") }
                    OutlinedButton(onClick = { deselected = allItems.map { it.id }.toSet() }) { Text("Clear all") }
                }
            }
        }

        Card(colors = CardDefaults.cardColors(containerColor = Color(0xFFF8FAFC))) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(
                    "Union wage growth (\$907.9K of modeled PBA/SOA/CSEA pressure) is the single largest driver in the 2027 model, but it's contractually locked and cannot be treated as a spending-reduction lever without a successor labor agreement — it stays on the pressure side of the budget, not here. Every dollar below is traceable to either a named formula input or an actual 2025→2026 account-level change in the Town's own 2026 Budget Supplement. Tap any item to test a package that leaves it out.",
                    color = Color(0xFF334155),
                    style = MaterialTheme.typography.bodySmall,
                )
                Text(
                    "PBA and SOA contracts both expire 12/31/2026 (CSEA is already locked through a ratified 2026-2029 agreement). New York law routes police/fire bargaining impasses to binding arbitration rather than legislative resolution, and comparable Long Island police contracts have taken 1-3+ years past expiration to settle — so the PBA/SOA figures above will likely remain placeholder estimates through the 2027 budget cycle, with any successor terms applied retroactively once reached.",
                    color = Color(0xFF334155),
                    style = MaterialTheme.typography.bodySmall,
                )
            }
        }

        CapGapCard(
            payrollPressureGap = payrollPressureGap,
            capGap = capGap,
            firmRecurringTotal = firmRecurringTotal,
            comboLowPct = comboLowPct,
            comboHighPct = comboHighPct,
        )
        RetirementLeverCard()

        ItemSection(
            title = "Personnel & Policy Savings",
            selectedAmount = personnelSelected,
            fullAmount = personnelFullTotal,
            items = personnelPolicyItems,
            isSelected = ::isSelected,
            onToggle = ::toggle,
            footer = "Six categories: policy or formula-driven savings that would require Board or contract action to actually capture.",
        )

        ItemSection(
            title = "Operational Growth Controls",
            selectedAmount = operationalSelected,
            fullAmount = operationalFullTotal,
            items = operationalItems,
            isSelected = ::isSelected,
            onToggle = ::toggle,
            footer = "Real account-level growth from the 2026 Budget Supplement, flagged for Board scrutiny before being carried forward as a permanent baseline.",
        )

        if (supplementItems.isNotEmpty()) {
            ItemSection(
                title = "Line-Item Trims · 2026 Supplement",
                selectedAmount = supplementSelected,
                fullAmount = supplementFullTotal,
                items = supplementItems,
                isSelected = ::isSelected,
                onToggle = ::toggle,
                footer = "Every controllable, non-mandated line the 2026 Supplement budgets more than 30% above its trailing actuals — trimmed back to that run-rate. Tagged FIRM (operating / professional services), MODERATE (capital / maintenance that fluctuates), or VOLATILE (price-driven fuel and energy). Mandated costs — pension, workers' comp, insurance, debt service — are excluded, since their growth is obligation, not waste.",
            )
        }

        SplitBoardCard()
    }
}

@Composable
private fun CapGapCard(
    payrollPressureGap: Double,
    capGap: Double,
    firmRecurringTotal: Double,
    comboLowPct: Int,
    comboHighPct: Int,
) {
    Card(shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = CardSurface)) {
        Column(modifier = Modifier.fillMaxWidth().padding(18.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("The real constraint", color = MutedText, style = MaterialTheme.typography.labelMedium, fontWeight = FontWeight.Bold)
            Text("Two different “gaps” — and which one actually binds", color = BrandNavy, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.titleMedium)
            Text(
                "The payroll-pressure gap above (${currency(payrollPressureGap)}) is the recurring cost of standing still. The number that actually forces a decision is bigger: the projected 2027 levy overshoots New York's 2% property-tax cap by about ${currency(capGap)} (a ~${CloseTheGap2027.predictedLevyPct}% levy against a ~${CloseTheGap2027.capBasePct}% ceiling). That is the real overage to resolve.",
                color = Color(0xFF334155), style = MaterialTheme.typography.bodySmall,
            )
            Text("Closing it without piercing the cap", color = BrandNavy, fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.bodyMedium)
            Text(
                "The unanimous retirement incentive plus only the firmest line trims — nothing volatile, no fund-balance raid, no override — already sum to roughly the whole gap:",
                color = Color(0xFF334155), style = MaterialTheme.typography.bodySmall,
            )
            GapTile("Retirement incentive", "${currency(CloseTheGap2027.RetirementIncentive.projectedSavingsLow)}–${currency(CloseTheGap2027.RetirementIncentive.projectedSavingsHigh)}", "Town projection · adopted 5–0", BrandMint)
            GapTile("Firm-confidence trims", currency(firmRecurringTotal), "Excludes volatile & capital-timing items", Color(0xFF1F5F8F))
            GapTile("Combined vs. the cap gap", "$comboLowPct–$comboHighPct%", "of the ${currency(capGap)} overage", BrandNavy)
        }
    }
}

@Composable
private fun GapTile(label: String, value: String, note: String, tint: Color) {
    Row(
        modifier = Modifier.fillMaxWidth().background(tint.copy(alpha = 0.08f), RoundedCornerShape(10.dp)).padding(12.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(label, color = MutedText, fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.labelMedium)
            Text(note, color = MutedText, style = MaterialTheme.typography.labelSmall)
        }
        Text(value, color = tint, fontWeight = FontWeight.Black, style = MaterialTheme.typography.titleMedium)
    }
}

@Composable
private fun RetirementLeverCard() {
    val ri = CloseTheGap2027.RetirementIncentive
    Card(shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = CardSurface)) {
        Column(modifier = Modifier.fillMaxWidth().padding(18.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text("Retirement incentive · ${ri.eligibleTotal} eligible", color = BrandNavy, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.titleMedium)
            Text(
                "The Town Board unanimously approved three voluntary retirement incentives on July 7, 2026 (${ri.resolutions}). The Town projects ${currency(ri.projectedSavingsLow)}–${currency(ri.projectedSavingsHigh)} in savings over ${ri.savingsWindow}.",
                color = Color(0xFF334155), style = MaterialTheme.typography.bodySmall,
            )
            ri.eligible.forEach { u ->
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text("${u.unit} · ${u.count} eligible", fontWeight = FontWeight.SemiBold, color = BrandNavy, style = MaterialTheme.typography.labelMedium, modifier = Modifier.padding(end = 8.dp))
                    Text(u.benefit, color = MutedText, style = MaterialTheme.typography.labelSmall)
                }
            }
            Text(ri.note, color = Color(0xFF94A3B8), style = MaterialTheme.typography.labelSmall)
        }
    }
}

@Composable
private fun SplitBoardCard() {
    Card(shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = CardSurface)) {
        Column(modifier = Modifier.fillMaxWidth().padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text("The best way forward through a split board", color = BrandNavy, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.titleMedium)
            Text(
                "Closing the gap has to pass a divided board: a Democratic Supervisor with a four-member Republican Council majority. Under NY Town Law the Supervisor prepares the tentative budget and the Council adopts it, so a durable plan needs both. These levers are ordered by how well each survives that split — least partisan first.",
                color = Color(0xFF334155), style = MaterialTheme.typography.bodySmall,
            )
            CloseTheGap2027.paths.forEachIndexed { i, p ->
                Column(
                    modifier = Modifier.fillMaxWidth().background(Color(0xFFF8FAFC), RoundedCornerShape(12.dp)).padding(12.dp),
                    verticalArrangement = Arrangement.spacedBy(4.dp),
                ) {
                    Row {
                        Text("${i + 1}", color = MutedText, fontWeight = FontWeight.Black, style = MaterialTheme.typography.labelMedium, modifier = Modifier.padding(end = 8.dp))
                        Text(p.name, fontWeight = FontWeight.SemiBold, color = BrandNavy, style = MaterialTheme.typography.bodyMedium, modifier = Modifier.weight(1f))
                    }
                    val (sc, sbg) = standingColors(p.standing)
                    Text(
                        p.standing.label, color = sc, fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelSmall,
                        modifier = Modifier.background(sbg, RoundedCornerShape(999.dp)).padding(horizontal = 8.dp, vertical = 2.dp),
                    )
                    Text("Closes: ${p.closes}", color = BrandMint, fontWeight = FontWeight.SemiBold, style = MaterialTheme.typography.labelMedium)
                    Text(p.politics, color = MutedText, style = MaterialTheme.typography.bodySmall)
                }
            }
            Text(CloseTheGap2027.pragmaticReading, color = Color(0xFF1E293B), style = MaterialTheme.typography.bodySmall, fontWeight = FontWeight.Medium)
            Text(
                "Board composition from the November 2025 results; budget roles per NY Town Law §§104–106. Cap-override mechanics per General Municipal Law §3-c (a 60% vote of the governing body).",
                color = Color(0xFF94A3B8), style = MaterialTheme.typography.labelSmall,
            )
        }
    }
}

private fun standingColors(s: CloseTheGap2027.Standing): Pair<Color, Color> = when (s) {
    CloseTheGap2027.Standing.AGREED, CloseTheGap2027.Standing.LOW_FRICTION -> Color(0xFF1F7A5C) to Color(0xFFD1FAE5)
    CloseTheGap2027.Standing.NEUTRAL -> Color(0xFF1E40AF) to Color(0xFFDBEAFE)
    CloseTheGap2027.Standing.ONE_TIME -> Color(0xFFB45309) to Color(0xFFFEF3C7)
    CloseTheGap2027.Standing.DELIBERATE -> Color(0xFF7C3AED) to Color(0xFFF3E8FF)
    CloseTheGap2027.Standing.BLUNT -> Color(0xFFB91C1C) to Color(0xFFFEE2E2)
}

@Composable
private fun ConfidenceBadge(confidence: String) {
    val (label, color, bg) = when (confidence) {
        "firm" -> Triple("FIRM", Color(0xFF1F7A5C), Color(0xFFD1FAE5))
        "moderate" -> Triple("MODERATE", Color(0xFFB45309), Color(0xFFFEF3C7))
        "volatile" -> Triple("VOLATILE", Color(0xFFB91C1C), Color(0xFFFEE2E2))
        else -> Triple(confidence.uppercase(), MutedText, Color(0xFFF1F5F9))
    }
    Text(
        label,
        color = color,
        fontWeight = FontWeight.Bold,
        style = MaterialTheme.typography.labelSmall,
        modifier = Modifier
            .background(bg, RoundedCornerShape(999.dp))
            .padding(horizontal = 6.dp, vertical = 2.dp),
    )
}

@Composable
private fun MetricTile(label: String, value: Double, color: Color, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier
            .background(color.copy(alpha = 0.08f), RoundedCornerShape(10.dp))
            .padding(10.dp),
    ) {
        Text(label.uppercase(), color = MutedText, style = MaterialTheme.typography.labelSmall, fontWeight = FontWeight.Bold)
        Text(currency(value), color = color, fontWeight = FontWeight.Black, style = MaterialTheme.typography.titleMedium)
    }
}

@Composable
private fun ItemSection(
    title: String,
    selectedAmount: Double,
    fullAmount: Double,
    items: List<SpendingReductionItem>,
    isSelected: (String) -> Boolean,
    onToggle: (String) -> Unit,
    footer: String,
) {
    Card(shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = CardSurface)) {
        Column(modifier = Modifier.fillMaxWidth().padding(18.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            Text(
                "$title — ${currency(selectedAmount)} of ${currency(fullAmount)}",
                fontWeight = FontWeight.Bold,
                color = BrandNavy,
                style = MaterialTheme.typography.titleMedium,
            )
            items.forEach { item ->
                val selected = isSelected(item.id)
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(if (selected) Color(0xFFF0FDF9) else Color(0xFFF8FAFC), RoundedCornerShape(12.dp))
                        .clickable { onToggle(item.id) }
                        .padding(12.dp),
                ) {
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                        Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.weight(1f)) {
                            if (selected) {
                                Icon(Icons.Filled.Check, contentDescription = null, tint = BrandMint, modifier = Modifier.height(16.dp))
                            }
                            Text(
                                item.title,
                                fontWeight = FontWeight.Bold,
                                color = BrandNavy,
                                style = MaterialTheme.typography.bodyMedium,
                                modifier = Modifier.padding(start = if (selected) 6.dp else 22.dp, end = 8.dp),
                            )
                            item.confidence?.let { ConfidenceBadge(it) }
                        }
                        Text(
                            currency(item.amount),
                            fontWeight = FontWeight.Bold,
                            color = if (selected) BrandMint else MutedText,
                            style = MaterialTheme.typography.bodyMedium,
                        )
                    }
                    Text(item.source, color = MutedText, style = MaterialTheme.typography.labelSmall, modifier = Modifier.padding(start = 22.dp, top = 3.dp))
                    Text(
                        item.rationale,
                        color = Color(0xFF94A3B8),
                        style = MaterialTheme.typography.labelSmall,
                        fontStyle = FontStyle.Italic,
                        modifier = Modifier.padding(start = 22.dp, top = 2.dp),
                    )
                }
            }
            Text(footer, color = Color(0xFF94A3B8), style = MaterialTheme.typography.labelSmall)
        }
    }
}
